#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}

if [[
    $# != 2
    ||
    ! ( $1 =~ ^[a-z]([-a-z0-9]{4,28}[a-z0-9])$ )
    ||
    ! ( $2 =~ ^([0-9]{1,3}\.){3}([0-9]{1,3})$ )
   ]]
then
    printf 'Usage: %s <gcp-project-name> <dotted-decimal-IPv4-address>\n' "$me" >&2
    exit 1
fi

gcp_project="$1"
gce_vm_ip="$2"

gce_vm_name_zone_ip_csv=${
    gcloud compute instances list \
        --format='csv(name,zone,networkInterfaces[0].networkIP)' \
        --project="$gcp_project" \
    |
    grep ",${gce_vm_ip//./\\.}\$"
}

gce_vm_name=${ cut --delimiter=',' --fields=1 <<< "$gce_vm_name_zone_ip_csv"; }
gce_vm_zone=${ cut --delimiter=',' --fields=2 <<< "$gce_vm_name_zone_ip_csv"; }

gcloud compute instances reset "$gce_vm_name" \
    --project="$gcp_project" \
    --zone="$gce_vm_zone" \
;
