#!/usr/bin/env bash

set -euo pipefail

brew_prefix=${ brew --prefix; }

declare -a input_paths
readarray -td ':' input_paths <<<"$PATH:"

output_path=''

for input_path in "${input_paths[@]:0:${#input_paths[@]}-1}"
do
    if [[ $input_path != "$brew_prefix"/* ]]
    then
        output_path+=":$input_path"
    fi
done

declare -a claude_args=()

for arg in "$@"
do
    claude_args+=("${arg@Q}")
done

PATH="$brew_prefix/bin$output_path" zsh --login -c "claude ${claude_args[*]}"
