#!/usr/bin/env bash

set -euo pipefail

readonly me=${0##*/}

if (($# != 0)); then
    printf 'Usage: %s\n' "$me" >&2
    exit 1
fi

new_p4_pass=${ pwgen 20 1; }
readonly new_p4_pass

p4 passwd \
    -O "${ op read op://Private/perforce/password; }" \
    -P "$new_p4_pass" \
;

op item edit perforce password="$new_p4_pass"
